### ISSUE TITLE
Cannot approve msig transactions "failed to sign message: Unexpected method"

### ISSUE THREAD

**Issue by grantslape** [Zondax/ledger-filecoin#103]
Attempting to approve msig transactions using `lotus v1.15.1` and ledger app `v0.22.2`, (Method # 3). Observing a failure to sign approval messages (method # 3). proposing messages (method # 2) appears to work just fine.

Example error using `lotus` CLI command `lotus msig approve  --from f1...  f2...   456`
```
2022-04-11T10:57:24.301-0500	WARN	rpc	go-jsonrpc@v0.1.5/handler.go:279	error in RPC call to 'Filecoin.WalletSign': Unexpected method
2022-04-11T10:57:24.301-0500	WARN	rpc	go-jsonrpc@v0.1.5/handler.go:279	error in RPC call to 'Filecoin.MpoolPushMessage': failed to sign message:
    github.com/filecoin-project/lotus/chain/messagesigner.(*MessageSigner).SignMessage
        <SNIP>/lotus/chain/messagesigner/messagesigner.go:73
  - Unexpected method
 ```
 
This issue does not occur when using ledger app `v0.18.5`, and thus appears to be resulting due to code changes between ledger app `v0.18.5` and `v0.22.2`

**Comment by rllola** [comment]
Hi @grantslape ,

We think we have identified the issue and are in the process of writing a fix. Thanks for letting us know.
