### ISSUE TITLE
Cannot withdraw using ledger hardware wallet as owner

### ISSUE THREAD

**Issue by yy1970** [Zondax/ledger-filecoin#107]
How to withdraw using ledger hardware wallet as owner.
Attempting to withdraw using lotus v1.15.1, (Method # 16). 
```
lotus-miner actor withdraw 10
ERROR: failed to sign message: Unexpected method
```

already in expert mode.

**Comment by rllola** [comment]
Hi @yy1970 

Your issue is the same as https://github.com/Zondax/ledger-filecoin/issues/103 and we are working on it. This is our priority.

Thank you for reporting it.

**Comment by yy1970** [comment]
Ok,Thanks.

**Comment by rllola** [comment]
A fix has been merged. Please wait for v0.22.4 to be released.

**Comment by yy1970** [comment]
it works now, thanks!
![image](https://user-images.githubusercontent.com/104660154/166907228-d2a67a5b-0fbe-4b22-afb3-90b5a7f0756f.png)
