### ISSUE TITLE
how to use `signRawBytes` 

### ISSUE THREAD

**Issue by 597800451** [Zondax/ledger-filecoin#140]
> Hi @597800451, could you open the issues related to the app in https://github.com/Zondax/ledger-filecoin/ 🙏 Have you checked this: `signRawBytes` this should allow you to sign a message but remember to add the prefix (`Filecoin Sign Bytes:\n`) Is this your issue or you are trying to sign an ETH message?

When I attempt to use signRawBytes, the Ledger returns `{return_code: 27012, error_message: 'Data is invalid : '}`, and my Ledger gets stuck displaying `RawBytes: Chunk:0` 
I suspect there may be an issue with the parameters I'm passing. Could you provide an example and teach me how to pass the parameters correctly? Here is my current code:

```
let message = 'hello'
let path = this._getPath(this.account)
try {
    
    let _msg = Buffer.from('Filecoin Sign Bytes:\n' + message, 'hex')
    
    let res = await filecoinApp.signRawBytes(path, _msg)
    console.log(res)
} catch (e) {
    console.log(e)
    throw e
}
```
![73efbc8f1c53b49145860cb8c56771f](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/ab1febe8-65f1-4d46-a622-558d0f21770b)

I later found the relevant test code, and when I attempted to use the test code, it returned an error: `{return_code: 27012, error_message: 'Data is invalid : Unsupported transaction type'}
`
```
 let path = this._getPath(this.account)
        try {
            const raw_bytes = this.genRandomData(30 * 1024);
            const prefix = Buffer.from("Filecoin Sign Bytes:\n");
            const txBlob = Buffer.concat([prefix, raw_bytes]);
            let res = await filecoinApp.signRawBytes(path, txBlob)
            console.log(res)
        } catch (e) {
            console.log(e)
            throw e
        }
```

_Originally posted by @597800451 in https://github.com/Zondax/ledger-filecoin-js/issues/67#issuecomment-1733013892_

**Comment by ftheirs** [comment]
Hi @597800451, you can check here how to use this command:
https://github.com/Zondax/ledger-filecoin/blob/8fa6a08fce60f395d75cd44608b872eb19aa7745/tests_zemu/tests/standard.test.ts#L457-L503

**Comment by 597800451** [comment]
> 你好@597800451，您可以在这里查看如何使用此命令：
> 
> https://github.com/Zondax/ledger-filecoin/blob/8fa6a08fce60f395d75cd44608b872eb19aa7745/tests_zemu/tests/standard.test.ts#L457-L503

Got it, turns out I needed to enable expert mode. Thanks!
