### ISSUE TITLE
GetAddress: Extend APDU specs and implementation 

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-filecoin#26]
- [x] Extend APDU specs

INS_GET_ADDR_SECP256K1 should return:
1- pubkey
2- address expressed as "Bytes" according to https://filecoin-project.github.io/specs/#protocol-1-libsecpk1-elliptic-curve-public-keys
3- address expressed as "String" according https://filecoin-project.github.io/specs/#protocol-1-libsecpk1-elliptic-curve-public-keys

Fields 2 and 3 should be prefixed by a byte indicating their length.

- [x] Adjust App implementation (https://github.com/Zondax/ledger-filecoin-app/pull/16)
- [x] Adjust JS library (https://github.com/Zondax/ledger-filecoin-js/pull/5)
- [x] Adjust Go library (https://github.com/Zondax/ledger-filecoin-go/pull/2)
- [x] Adjust Rust library (https://github.com/Zondax/ledger-filecoin-rs/pull/2)

**Comment by rllola** [comment]
I think all the PR are ready to be merged for the libraries.
