### ISSUE TITLE
Signing clicking path has changed

### ISSUE THREAD

**Issue by rllola** [Zondax/ledger-filecoin#43]
In order to sign using v0.15, doing left, right & both won't work anymore.

New click path : both, right & both seems to work tho. See zemu test in `filecoin-rs`.

It is not clear what has been changed in the app or the sdk and if it has others ramifications... as far as I know it doesn't.

**Comment by jleni** [comment]
Yes, left in the first item is not possible anymore. Ideally Ledger prefer users to navigate along the data. There is still, as you found, the option to click both to skip the review.
