### ISSUE TITLE
Add screen to display address on the device.

### ISSUE THREAD

**Issue by defunctzombie** [Zondax/ledger-filecoin#51]
A nice security enhancement is to display the Filecoin address on the device (rather than relying on a connected UI). This provides an additional verification around the user's account address.

Happy to clarify more if this post is not descriptive enough.

**Comment by jleni** [comment]
This feature is already exist in this app, it is exposed and part of the zemu test.
Let me know if you need more info. Are you trying to integrate the app somewhere?

**Comment by defunctzombie** [comment]
@jleni Were in the app is this? I've installed v0.17.2 on a test device and clicked through the app's menus. I did not see any settings or screen to show the address.
