### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-filecoin#6]

**Comment by jleni** [comment]
Thanks @jnthnvctr ! 
The small icons (pngs in the attached file) need to be GIF 16x16 1-bit ? 
Look at the end here: https://github.com/ZondaX/ledger-filecoin-app/blob/05b42c7426ad4bdee7ece55314b3a9574818b0f8/nanos_icon.gif

**Comment by jnthnvctr** [comment]
Ah! Will ask them to correct - thanks for catching
