### ISSUE TITLE
can't make load on Nano X

### ISSUE THREAD

**Issue by IPFSMain-Official** [Zondax/ledger-filecoin#62]
When I execute make I get the following information, TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=1.6.0, and `make load` show the following error
Invalid status 6484 (Are you using the correct targetId?)

**Comment by Krysme** [comment]
Would you mind sharing how you solved this one? 
I'm having the same issue here.
