### ISSUE TITLE
gasFeeCap and gasPremium fields are swapped in parser

### ISSUE THREAD

**Issue by davidad** [Zondax/ledger-filecoin#63]
When reviewing transactions on my Ledger's display, the Gas Premium value is displayed as "Gas Fee Cap" and vice versa. I suspect this is because the [parser code](https://github.com/Zondax/ledger-filecoin/blob/master/app/src/parser_impl.c#L295-L303) does not match the [message format](https://github.com/filecoin-project/lotus/blob/dc3d17c9eae5b9acfe587541d0e6ef3245537a33/chain/types/message.go#L41-42) regarding this sequencing.

**Comment by rllola** [comment]
Hey @davidad !

Thanks for reporting this issue. It has been fixed as you can see.
