### ISSUE TITLE
Allow arbitrary methods in expert mode

### ISSUE THREAD

**Issue by Stebalien** [Zondax/ledger-filecoin#65]
Currently, only methods 0-7 are allowed. Unfortunately, this means:

1. Ledgers cannot be used for miner "owner" keys.
2. Some multisig methods may not be allowed either.

**Comment by hyunmoon** [comment]
Very curious as well.

**Comment by mikereinhart** [comment]
We're also interested in seeing this issue resolved, particularly the multisig methods - thanks.

**Comment by ohJohanZ** [comment]
Please fix this issue.
