### ISSUE TITLE
Gas Fee Cap and Gas Premium are wrongly displayed

### ISSUE THREAD

**Issue by PatrickDeuse** [Zondax/ledger-filecoin#66]
When reviewing a transaction on the ledger device the Gas Premium shows the Gas Fee Cap and vice versa.

0.18.2

ledger nanoX, newest ledger firmware, updated minutes ago.

found when using https://wallet.glif.io, reproducible

**Comment by rllola** [comment]
Hi @PatrickDeuse 

Thanks for reporting. The issue has been fixed. I think it has not been released yet. We are going to create a new release soon.
