### ISSUE TITLE
change owner sign error

### ISSUE THREAD

**Issue by olier** [Zondax/ledger-filecoin#82]
![image](https://user-images.githubusercontent.com/6144637/138452307-6a9ccd38-140a-402c-a1a6-e303dbc43c97.png)
![image](https://user-images.githubusercontent.com/6144637/138452330-dcf52ca3-e6df-4ecf-8b9a-a99412807bdb.png)

**Comment by jleni** [comment]
related 
issue #76 
PR #79

**Comment by ftheirs** [comment]
Closed by https://github.com/Zondax/ledger-filecoin/pull/84
