### ISSUE TITLE
Signing deals with Ledger

### ISSUE THREAD

**Issue by Beanow** [Zondax/ledger-filecoin#86]
Supporting this would be marvelous for regular end-users indeed :]
If I've skimmed the code correctly, the Ledger app doesn't have a path for signing deals.

If so it makes sense it's not supported by Lotus: https://github.com/filecoin-project/lotus/issues/5386
As I understand expert mode doesn't create a workaround to blindly sign these either.

The interactive `lotus client deal --from f1...ledger-address` steps could be inspiration for the Ledger UI to review.

```
Data CID (from lotus client import):
Deal duration (days):
Make this a verified deal? (yes/no):
Miner Addresses (f0.. f0..), none to find:

Proposing from f1...ledger-address
	Balance: 12.345 FIL

Piece size: 32KiB (Payload size: 19.87KiB)
Duration: 4321h0m0s
Total price: ~0 FIL (0 FIL per epoch)
Verified: true

Accept (yes/no):
```

But a quick fix of "expert" blind signing with appropriate warnings might be reusable later, should future variants on deals be unsupported in the main review flow.

**Comment by ftheirs** [comment]
Implemented here: https://github.com/Zondax/ledger-filecoin/pull/130
